
os:
   - linux
   - osx

dist: xenial
sudo: required

addons:
  apt:
    packages:
      - libsdl2-dev

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

language: cpp

script:
   - mkdir build_natve
   - cd build_native
   - cmake ..
   - make

compiler:
   - clang
   - gcc
